#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

INPUT=$2

case "$1" in 
start-service)
   echo "Starting $INPUT..."
   systemctl start $INPUT
   ;;
stop-service)
   echo "Stop $INPUT..."
   systemctl stop $INPUT
   ;;
restart-service)
   echo "Restarting $INPUT..."
   $0 stop-service $INPUT
   $0 start-service $INPUT
   ;;
service-status)
   systemctl status $INPUT
   ;;
file-info)
   file=$(find / -name $INPUT | wc -l)
   if  [ $file -eq 0 ];then
       echo "No file found"
   else
       for file in $(find / -name $INPUT);
       do echo;echo;
       echo "###########################";
       echo "File Metadata";
       echo "###########################";
       echo;
       stat $file;
       echo;echo;
       echo "###########################";
       echo "File Content";
       echo "###########################";
       echo;cat $file;echo;echo;
       done
   fi
   ;;
install-package)
   /usr/bin/apt install $INPUT -y 
   ;;
remove-package)
   /usr/bin/apt-get remove $INPUT -y 
   ;;
       
 
*)
   echo "Usage: $0 {stop-service | start-service | restart-service | service-status | file-info | install-package | remove-packagesss}"
esac

exit 0 
