#!/bin/bash
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

echo "#######################################"
echo "######## APPLICATION DEPLOYED #########"
echo "#######################################"
echo "Apache2"
echo "PHP"
echo "#######################################"
echo "############ TAG DEPLOYED #############"
echo "#######################################"
echo "Source - https://github.com/sltestconfig/deployment"
echo "Tag - $(cat /root/deployment/application-deployment/apptag)"
echo "#######################################"
echo "#######################################"


