#!/bin/sh
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

printf "\n"
printf "\n"
printf "######## APPLICATION DEPLOYED #########\n"
printf "Apache2\n"
printf "PHP\n"
printf "########################################\n"
