#!/bin/sh
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

printf "\n"
printf "\n"
printf "###################################################"
printf "######## APPLICATION DEPLOYED #########"
printf "Apache2"
printf "PHP"
printf "############## TAG INFO ###############"
TAG=$(git rev-parse --short HEAD)
printf  "TAG DEPLOYED $TAG"
print "###################################################"
